version: '3'
services:
  db:
    image: postgres
    ports:
          - "45432:5432"
  web:
    build: .
    command: /myapp/start.sh
    volumes:
      - .:/myapp
    ports:
      - "3003:3000"
    volumes:
      - .:/myapp
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres@db:5432/development